// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5KHOW6TQ7kry2lnjVx2MmNcAbLjMguUU',
    appId: '1:841608660208:web:9ccd68bfc3c2d5b9cf6e35',
    messagingSenderId: '841608660208',
    projectId: 'fgp-equity',
    authDomain: 'fgp-equity.firebaseapp.com',
    storageBucket: 'fgp-equity.firebasestorage.app',
    measurementId: 'G-RDV5XXPK94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQyFS8z7nZCCmi_-nnqHH-xlauxjUDaew',
    appId: '1:841608660208:android:c627f278644232b3cf6e35',
    messagingSenderId: '841608660208',
    projectId: 'fgp-equity',
    storageBucket: 'fgp-equity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9TtHhN34tog9W9UiWC-UZH0G-vRUYqWI',
    appId: '1:841608660208:ios:fb4fc284cd396d5ccf6e35',
    messagingSenderId: '841608660208',
    projectId: 'fgp-equity',
    storageBucket: 'fgp-equity.firebasestorage.app',
    iosBundleId: 'com.example.fgp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9TtHhN34tog9W9UiWC-UZH0G-vRUYqWI',
    appId: '1:841608660208:ios:fb4fc284cd396d5ccf6e35',
    messagingSenderId: '841608660208',
    projectId: 'fgp-equity',
    storageBucket: 'fgp-equity.firebasestorage.app',
    iosBundleId: 'com.example.fgp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5KHOW6TQ7kry2lnjVx2MmNcAbLjMguUU',
    appId: '1:841608660208:web:07bc828b5416c6b3cf6e35',
    messagingSenderId: '841608660208',
    projectId: 'fgp-equity',
    authDomain: 'fgp-equity.firebaseapp.com',
    storageBucket: 'fgp-equity.firebasestorage.app',
    measurementId: 'G-JMKV68G4Z5',
  );
}
